name: pressure_predict_gpu
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
    - tensorflow_gpu==2.10
    - scipy
    - numpy
    - matplotlib
    - jupyterlab
    - tf2onnx